import {
  apiTutorial,
  axiosRouterExercise,
  digitalClock,
  fireBlog,
  fireContact,
  languageCards,
  MovieApp,
  randomUserOne,
  randomUserTwo,
  RecipeApp,
  reviewsProject,
  stopWatch,
  taskTracker,
  TourPlaces,
  weatherApp,
} from "../assets/projectPreviews";

const reactData = [
  {
    id: 1,
    imgSrc: { fireBlog },
    projectName: "Fire Blog",
    overview: [
      " In this project, I designed a Fire Blog with many features.",
      "I used context API for state management, Firebase for authentication, and Firestore database for CRUD operations.",
    ],
    link: "https://github.com/esadakman/FireBlog-Milestone",
  },
  {
    id: 2,
    imgSrc: { fireContact },
    projectName: "FireContact",
    overview: [
      "In this project, I designed a Contact App for understanding CRUD operations.",
      "I used Firebase Realtime Database for database.",
      "User can update the list by entering name, phone number and gender information.And also user can delete or fix any contact from table..",
    ],
    link: "https://github.com/esadakman/firecontact-app",
  },
  {
    id: 3,
    imgSrc: { MovieApp },
    projectName: "Movie App",
    overview: [
      "In this project, I designed a Movie App with many features. I provided the movie information with the TMDB API.",
      "I used Firebase for authentication.",
      "The user can log in and register with both their email address and their Google account.",
    ],
    link: "https://github.com/esadakman/movie-app-firebase",
},
{
    id: 4,
    imgSrc: {RecipeApp},
    projectName: "Recipe App",
    overview: [
      "In this project i tried to make a recipe app.",
      "I used local storage for authentication.",
      "After login you can search food's recipe by their name and type.",
    ], 
    link: "https://github.com/esadakman/recipe-app",
  },
  {
    id: 5,
    imgSrc: "9aYRY2B5Jgj",
    projectName: "Robbie",
    overview: "Mc Harg",
    link: "rmcharg4@scientificamerican.com",
  },
  {
    id: 6,
    imgSrc: "ccKCMM",
    projectName: "Niki",
    overview: "Daber",
    link: "ndaber5@army.mil",
  },
  {
    id: 7,
    imgSrc: "1R3G2WJ",
    projectName: "Rana",
    overview: "Gyrgorwicx",
    link: "rgyrgorwicx6@booking.com",
  },
  {
    id: 8,
    imgSrc: "l6Fip9FINxzR",
    projectName: "Johnette",
    overview: "Torricella",
    link: "jtorricella7@discuz.net",
  },
  {
    id: 9,
    imgSrc: "pT35uEWU5y",
    projectName: "Kristoforo",
    overview: "Slinn",
    link: "kslinn8@scribd.com",
  },
  {
    id: 10,
    imgSrc: "ElyzUYgyyWC",
    projectName: "Wye",
    overview: "Bushrod",
    link: "wbushrod9@infoseek.co.jp",
  },
  {
    id: 11,
    imgSrc: "bnpqvhjNN",
    projectName: "Aline",
    overview: "Boydle",
    link: "aboydlea@woothemes.com",
  },
  {
    id: 12,
    imgSrc: "l4LSCXxY",
    projectName: "Dall",
    overview: "Ettritch",
    link: "dettritchb@wiley.com",
  },
  {
    id: 13,
    imgSrc: "w5E58sLnrvzf",
    projectName: "Wynn",
    overview: "Vautier",
    link: "wvautierc@dagondesign.com",
  },
  {
    id: 14,
    imgSrc: "Ne8TDr",
    projectName: "Cami",
    overview: "Pfaffe",
    link: "cpfaffed@auda.org.au",
  },
];

export default reactData;
